### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by TheAlbanian** [goXXip/xtreamuiR14#1]
Hello you have more info how to enter on admin because with dhis files have problem on admin panel. 
please upload original SQL.

**Comment by goXXip** [comment]
First
sudo apt install phyton
wget https://xtream-ui.com/install/install.py
chmod +x install.py
phyton install.py

1 select main and wait to install.
is finished run again phyton install.py and select admin and wait to install.

and later install xtreamuir14
